// data.js — locked copy from BRIEF.md v2.0, UA + EN
window.WF_CONTENT = {
  ua: {
    nav: ["Партнери", "Роботи", "Послуги", "Процес", "Про мене", "Контакт"],
    nav_hrefs: ["#partners", "#work", "#services", "#process", "#who", "#contact"],
    cta_portal: "Мій кабінет",
    cta_primary: "Обговорити проєкт",
    cta_secondary: "Подивитися роботи",
    hero: {
      h1_options: [
        ["Я Ілля. Будую автоматизації", "для команд, що виросли", "з Excel."],
        ["Я Ілля. Автоматизую те,", "що ваша команда робить", "руками."],
        ["Менше клацань.", "Більше зроблено.", ""],
      ],
      sub: "Луцьк · Україна · 6 років у продуктовій розробці",
    },
    live: [
      "implementing webhook retry logic in workflo",
      "writing case study about retail integration",
      "review PR for client CRM portal",
      "shipping new agent prompts to staging",
    ],
    live_label: "зараз:",
    live_ago: ["12m ago", "2h ago", "8m ago", "1h ago"],
    services: {
      label: "// services",
      h2: "Чотири типи робіт",
      items: [
        {
          num: "01",
          name: "Інтеграції та API",
          line: "Коли дві системи не розмовляють між собою.",
          examples: "CRM ↔ 1C · Notion ↔ Telegram · форми → внутрішня БД · GoogleSheets → email-розсилка з тригером.",
          tools: ["TypeScript", "Node", "Python", "REST", "webhooks", "queues"],
        },
        {
          num: "02",
          name: "AI-агенти та workflow",
          line: "Коли потрібен агент, який щось робить, а не просто чатить.",
          examples: "Бот саппорту з контекстом ваших даних · агент-аналітик для звітів · генератор пропозицій з CRM · processor для документів.",
          tools: ["OpenAI", "Anthropic", "LangChain", "RAG", "vector DBs"],
        },
        {
          num: "03",
          name: "Внутрішні портали та CRM",
          line: "Коли готові SaaS не покривають ваші процеси.",
          examples: "Портал замовлень для клієнтів · кастомний CRM під специфіку · dashboard з real-time даних.",
          tools: ["Next.js", "React", "Postgres", "Prisma"],
        },
        {
          num: "04",
          name: "Автоматизація рутини",
          line: "Коли людина робить те, що має робити скрипт.",
          examples: "Парсинг даних з сайтів · генерація документів з шаблонів · заплановані звіти · scrapers · монітори.",
          tools: ["Python", "n8n", "Make", "GitHub Actions"],
        },
      ],
    },
    partners: {
      label: "// partners",
      h2: "Партнери",
      subtitle: "5 команд, з якими працюю. Клік на партнера — відкриває його сторінку з роботою.",
    },
    scale: {
      label: "// scale",
      h2: "Масштаб",
      subtitle: "Що тут показано явно — верхівка айсбергу. Більшість проєктів — під NDA.",
      stats: [
        { v: "12", k: "total projects" },
        { v: "7", k: "companies" },
        { v: "4 роки", k: "in automation" },
        { v: "4", k: "countries" },
        { v: "5", k: "public case studies" },
        { v: "7", k: "under nda" },
      ],
      nda_head: "### under NDA · 7 проєктів",
      nda_hint: "Компанії не називаю — під NDA. На запит можу надати референси від клієнтів.",
      nda: [
        { tag: "fintech-eu",  name: "payment orchestrator", year: "2025", duration: "8 тижнів",  summary: "Роутинг платежів між 4 провайдерами · фолбек + ретраї", impact: ["sub-50ms latency p99", "4 системи зведено"] },
        { tag: "healthtech",  name: "booking automation",   year: "2024", duration: "12 тижнів", summary: "Самозапис пацієнтів · 8 клінік",                       impact: ["−74% phone load", "24/7 self-service"] },
        { tag: "b2b-saas-de", name: "internal CRM",          year: "2024", duration: "6 тижнів",  summary: "Внутрішній CRM для sales · 50 користувачів",          impact: ["80% adoption за місяць"] },
        { tag: "media-co",    name: "content pipeline",      year: "2023", duration: "4 тижні",   summary: "AI-пайплайн рерайтера · ≈3k статей/міс",              impact: ["5× вихідний об'єм"] },
        { tag: "legaltech",   name: "document parser",       year: "2023", duration: "3 тижні",   summary: "Парсер контрактів у структуровані дані",              impact: ["95% точність витягу"] },
        { tag: "edtech-de",   name: "payment flow",          year: "2023", duration: "5 тижнів",  summary: "Онлайн-оплата курсів · EUR/PLN/CZK",                  impact: ["+18% conversion"] },
        { tag: "retail-pl",   name: "inventory sync",        year: "2022", duration: "6 тижнів",  summary: "Синхронізація складів · 12 точок",                    impact: ["−6h/day введення", "99.8% точність"] },
      ],
    },
    cases: {
      label: "// work",
      h2: "Що я зробив",
      items: [
        { num: "01", slug: "retail-1c-integration",
          name: "Інтеграція 1С ↔ Telegram для логістики",
          year: "2025", duration: "6 тижнів",
          context: "50 водіїв вручну скидали накладні в чат — без структури, з помилками.",
          metrics: ["−87% часу на обробку замовлень", "+€12k додаткового MRR", "4 системи з'єднано в один потік"],
          stack: ["Next.js", "Postgres", "1C API", "Telegram Bot API", "Anthropic"],
        },
        { num: "02", slug: "ai-support-agent",
          name: "AI-агент саппорту для SaaS",
          year: "2024", duration: "4 тижні",
          context: "First-response 14 годин, нові користувачі churning на третій день.",
          metrics: ["92% auto first response", "+24% CSAT", "~$3.2k/міс економія"],
          stack: ["Anthropic Claude", "RAG", "Pinecone", "Python", "Slack API"],
        },
        { num: "03", slug: "custom-crm-logistics",
          name: "Кастомний CRM для логістичного оператора",
          year: "2025", duration: "8 тижнів",
          context: "Три системи (склад, доставка, фінанси) — нічна ручна синхронізація.",
          metrics: ["400 годин/міс економії", "3 системи → 1 портал", "Real-time tracking"],
          stack: ["Next.js", "Postgres", "Prisma", "Redis", "Mapbox"],
        },
        { num: "04", slug: "market-parser",
          name: "Парсер ринкових даних для агенції",
          year: "2024", duration: "2 тижні",
          context: "Аналітик витрачав 18 годин на тиждень на ручний збір.",
          metrics: ["18 год → 12 хв щодня", "+200% частота звітів", "0 помилок копіювання"],
          stack: ["Python", "Playwright", "GitHub Actions", "Sheets API"],
        },
        { num: "05", slug: null, // own product, no project page
          name: "Workflo",
          year: "продукт у розробці", duration: "beta Q3 2026",
          context: "Платформа для команд, які працюють із замовленнями. Усе на одній сторінці.",
          metrics: ["240+ у waitlist", "3 пілотні команди", "beta Q3 2026"],
          stack: ["Next.js", "Postgres", "Prisma", "Anthropic", "Tailwind"],
        },
      ],
    },
    process: {
      label: "// process",
      h2: "Як виглядає робота зі мною",
      items: [
        { num: "01", name: "Дзвінок 30 хв",       desc: "Розбираємо ваш процес, фіксуємо болі, визначаємо чи я підходжу. Без зобов'язань." },
        { num: "02", name: "Технічна пропозиція", desc: "Через 3–5 днів — документ із обсягом, технологіями, дедлайном і фіксованою ціною. Без «time & material»." },
        { num: "03", name: "Розробка",            desc: "Щотижневі demo. Ви бачите прогрес кожні 7 днів — без сюрпризів. Slack або Telegram-канал проєкту." },
        { num: "04", name: "Запуск",              desc: "Деплой, тестування з командою, навчання, документація. Перші 2 тижні підтримки безкоштовно." },
        { num: "05", name: "Підтримка (опціонально)", desc: "Місячна підписка на оновлення, моніторинг, нові фічі — за бажанням. Без неї нічого не зламається." },
      ],
    },
    spotlight: {
      label: "// spotlight",
      status: "in development · beta Q3 2026",
      name: "Workflo",
      desc: "Платформа для команд, які працюють із замовленнями. Все на одній сторінці: замовлення, документи, фінанси, статуси в реальному часі. Без зайвого.",
      market: "Ринок: B2B-компанії 5–50 людей, які зараз тримають це в Notion, Excel або кустарному CRM.",
      cta_form: "Дізнатися першим коли запустимо beta",
      cta_email_ph: "you@email.com",
      cta_github: "Або подивитися на GitHub",
    },
    about: {
      label: "// who",
      body: [
        "Я з Луцька. Програмую з 2018-го, останні 4 роки — автоматизую процеси для бізнесів, які виросли з Excel.",
        "До цього: продуктова команда в логістичному стартапі, фронтенд для української fintech-компанії, freelance-проєкти для агенцій у ЄС.",
        "",
        "Чому я цим займаюся:",
        "Більшість команд, які я бачив, втрачають по 10–20 годин на тиждень на роботу, яку має робити скрипт. Хтось копіює дані між таблицями, хтось вручну формує звіти, хтось пише одне й те саме email щодня.",
        "",
        "Я роблю так, щоб цього не було.",
        "Workflo — це мій спосіб дати цю можливість командам, які не можуть собі дозволити окремого розробника.",
      ],
    },
    contact: {
      label: "// contact",
      h2: "Поговоримо?",
      sub: "Розкажіть коротко про проєкт — поверну протягом 24 годин у будні.",
      f_name: "Ім'я",
      f_contact: "Telegram або email",
      f_message: "Опис проєкту",
      send: "Надіслати",
      or: "або напряму",
      channels: [
        { kind: "Telegram", value: "@vasulenkoillia" },
        { kind: "Email",    value: "illia@workflo.space" },
        { kind: "GitHub",   value: "VasulenkoIllia" },
      ],
    },
    footer: {
      built: "built in lutsk · 2026",
    },
  },
  en: {
    nav: ["Partners", "Work", "Services", "Process", "About", "Contact"],
    nav_hrefs: ["#partners", "#work", "#services", "#process", "#who", "#contact"],
    cta_portal: "Client portal",
    cta_primary: "Start a project",
    cta_secondary: "See work",
    hero: {
      h1_options: [
        ["I'm Illia. I build automations", "for teams that outgrew", "Excel."],
        ["I'm Illia. I automate what your", "team does", "by hand."],
        ["Fewer clicks.", "More done.", ""],
      ],
      sub: "Lutsk · Ukraine · 6 years building product",
    },
    live: [
      "implementing webhook retry logic in workflo",
      "writing case study about retail integration",
      "reviewing PR for client CRM portal",
      "shipping new agent prompts to staging",
    ],
    live_label: "now:",
    live_ago: ["12m ago", "2h ago", "8m ago", "1h ago"],
    services: {
      label: "// services",
      h2: "Four kinds of work",
      items: [
        { num: "01", name: "Integrations & APIs", line: "When two systems don't talk to each other.",
          examples: "CRM ↔ 1C · Notion ↔ Telegram · forms → internal DB · Sheets → triggered email campaigns.",
          tools: ["TypeScript", "Node", "Python", "REST", "webhooks", "queues"] },
        { num: "02", name: "AI agents & workflow", line: "When you need an agent that does things, not just chats.",
          examples: "Support bot with your data context · analyst agent for reports · proposal generator from CRM · document processors.",
          tools: ["OpenAI", "Anthropic", "LangChain", "RAG", "vector DBs"] },
        { num: "03", name: "Internal portals & CRM", line: "When off-the-shelf SaaS doesn't fit your process.",
          examples: "Order portal for clients · custom CRM matching your specifics · real-time dashboards.",
          tools: ["Next.js", "React", "Postgres", "Prisma"] },
        { num: "04", name: "Routine automation", line: "When a human does what a script should do.",
          examples: "Web data parsing · template-based document generation · scheduled reports · scrapers · monitors.",
          tools: ["Python", "n8n", "Make", "GitHub Actions"] },
      ],
    },
    partners: {
      label: "// partners",
      h2: "Partners",
      subtitle: "5 teams I work with. Click a partner to open their page.",
    },
    scale: {
      label: "// scale",
      h2: "Scale",
      subtitle: "What is shown above is the tip of the iceberg. Most projects are under NDA.",
      stats: [
        { v: "12", k: "total projects" },
        { v: "7", k: "companies" },
        { v: "4 years", k: "in automation" },
        { v: "4", k: "countries" },
        { v: "5", k: "public case studies" },
        { v: "7", k: "under nda" },
      ],
      nda_head: "### under NDA · 7 projects",
      nda_hint: "Companies not named — under NDA. References available on request.",
      nda: [
        { tag: "fintech-eu",  name: "payment orchestrator", year: "2025", duration: "8 weeks",  summary: "Routing payments across 4 providers · fallback + retry", impact: ["sub-50ms latency p99", "4 systems unified"] },
        { tag: "healthtech",  name: "booking automation",   year: "2024", duration: "12 weeks", summary: "Patient self-booking · 8 clinics",                       impact: ["−74% phone load", "24/7 self-service"] },
        { tag: "b2b-saas-de", name: "internal CRM",          year: "2024", duration: "6 weeks",  summary: "Internal CRM for sales · 50 users",                     impact: ["80% adoption in 1 month"] },
        { tag: "media-co",    name: "content pipeline",      year: "2023", duration: "4 weeks",  summary: "AI rewriter pipeline · ~3k articles/mo",                impact: ["5× output volume"] },
        { tag: "legaltech",   name: "document parser",       year: "2023", duration: "3 weeks",  summary: "Contract parser to structured data",                    impact: ["95% extraction accuracy"] },
        { tag: "edtech-de",   name: "payment flow",          year: "2023", duration: "5 weeks",  summary: "Online course payments · EUR/PLN/CZK",                   impact: ["+18% conversion"] },
        { tag: "retail-pl",   name: "inventory sync",        year: "2022", duration: "6 weeks",  summary: "Warehouse sync · 12 stores",                            impact: ["−6h/day data entry", "99.8% accuracy"] },
      ],
    },
    cases: {
      label: "// work",
      h2: "What I shipped",
      items: [
        { num: "01", slug: "retail-1c-integration", name: "1C ↔ Telegram integration for logistics", year: "2025", duration: "6 weeks",
          context: "50 drivers dropped invoices in chat manually — no structure, errors compounding.",
          metrics: ["−87% order processing time", "+€12k additional MRR", "4 systems joined in one flow"],
          stack: ["Next.js", "Postgres", "1C API", "Telegram Bot API", "Anthropic"] },
        { num: "02", slug: "ai-support-agent", name: "AI support agent for SaaS", year: "2024", duration: "4 weeks",
          context: "14h first-response time, new users churning on day three.",
          metrics: ["92% auto first response", "+24% CSAT", "~$3.2k/mo saved"],
          stack: ["Anthropic Claude", "RAG", "Pinecone", "Python", "Slack API"] },
        { num: "03", slug: "custom-crm-logistics", name: "Custom CRM for logistics operator", year: "2025", duration: "8 weeks",
          context: "Three systems (warehouse, delivery, finance) — nightly manual sync.",
          metrics: ["400 hrs/mo saved", "3 systems → 1 portal", "Real-time tracking"],
          stack: ["Next.js", "Postgres", "Prisma", "Redis", "Mapbox"] },
        { num: "04", slug: "market-parser", name: "Market data parser for agency", year: "2024", duration: "2 weeks",
          context: "Analyst spent 18 hours a week on manual collection.",
          metrics: ["18h → 12min daily", "+200% report cadence", "0 copy-paste errors"],
          stack: ["Python", "Playwright", "GitHub Actions", "Sheets API"] },
        { num: "05", slug: null, name: "Workflo", year: "in development", duration: "beta Q3 2026",
          context: "Platform for teams that run on orders. Everything on one page.",
          metrics: ["240+ waitlist", "3 pilot teams", "beta Q3 2026"],
          stack: ["Next.js", "Postgres", "Prisma", "Anthropic", "Tailwind"] },
      ],
    },
    process: {
      label: "// process",
      h2: "What working together looks like",
      items: [
        { num: "01", name: "30-min call",         desc: "We unpack your process, log the pains, and decide whether I'm a fit. No strings attached." },
        { num: "02", name: "Technical proposal",  desc: "In 3–5 days — a doc with scope, tech, deadlines and fixed price. No 'time & material'." },
        { num: "03", name: "Build",               desc: "Weekly demo. You see progress every 7 days — no surprises. Slack or Telegram channel for the project." },
        { num: "04", name: "Launch",              desc: "Deploy, test with the team, train, document. First 2 weeks of support included." },
        { num: "05", name: "Support (optional)",  desc: "Monthly subscription for updates, monitoring, new features — if you want it. Nothing breaks without it." },
      ],
    },
    spotlight: {
      label: "// spotlight",
      status: "in development · beta Q3 2026",
      name: "Workflo",
      desc: "Platform for teams that run on orders. Everything on one page: orders, documents, finance, real-time status. Nothing extra.",
      market: "Market: B2B teams of 5–50 currently holding this in Notion, Excel or a homegrown CRM.",
      cta_form: "Be first to know when beta ships",
      cta_email_ph: "you@email.com",
      cta_github: "Or take a look on GitHub",
    },
    about: {
      label: "// who",
      body: [
        "I'm from Lutsk. Coding since 2018, the last 4 years automating processes for businesses that outgrew Excel.",
        "Before this: product team at a logistics startup, frontend for a Ukrainian fintech, freelance projects with EU agencies.",
        "",
        "Why I do this:",
        "Most teams I've seen lose 10–20 hours a week on work that should be done by a script. Someone copying data between tables, someone hand-building reports, someone typing the same email every day.",
        "",
        "I make sure that doesn't happen.",
        "Workflo is my way of giving the same capability to teams that can't afford a dedicated developer.",
      ],
    },
    contact: {
      label: "// contact",
      h2: "Let's talk?",
      sub: "Tell me briefly about the project — I'll respond within 24 business hours.",
      f_name: "Name",
      f_contact: "Telegram or email",
      f_message: "Project description",
      send: "Send",
      or: "or directly",
      channels: [
        { kind: "Telegram", value: "@vasulenkoillia" },
        { kind: "Email",    value: "illia@workflo.space" },
        { kind: "GitHub",   value: "VasulenkoIllia" },
      ],
    },
    footer: {
      built: "built in lutsk · 2026",
    },
  },
};
